//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRT.Client.TrackerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrackerService.ITrackerService")]
    public interface ITrackerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackerService/RegistreraKoordinater", ReplyAction="http://tempuri.org/ITrackerService/RegistreraKoordinaterResponse")]
        string RegistreraKoordinater(int kontainerId, System.DateTime tidpunkt, string longitude, string latitude, string noggranhet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackerService/RegistreraKoordinaterOchStatus", ReplyAction="http://tempuri.org/ITrackerService/RegistreraKoordinaterOchStatusResponse")]
        string RegistreraKoordinaterOchStatus(int kontainerId, System.DateTime tidpunkt, string longitude, string latitude, string noggranhet, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrackerService/HämtaKontainrar", ReplyAction="http://tempuri.org/ITrackerService/HämtaKontainrarResponse")]
        WRT.Core.BLL.Kontainer[] HämtaKontainrar();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrackerServiceChannel : WRT.Client.TrackerService.ITrackerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrackerServiceClient : System.ServiceModel.ClientBase<WRT.Client.TrackerService.ITrackerService>, WRT.Client.TrackerService.ITrackerService {
        
        public TrackerServiceClient() {
        }
        
        public TrackerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrackerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrackerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegistreraKoordinater(int kontainerId, System.DateTime tidpunkt, string longitude, string latitude, string noggranhet) {
            return base.Channel.RegistreraKoordinater(kontainerId, tidpunkt, longitude, latitude, noggranhet);
        }
        
        public string RegistreraKoordinaterOchStatus(int kontainerId, System.DateTime tidpunkt, string longitude, string latitude, string noggranhet, string status) {
            return base.Channel.RegistreraKoordinaterOchStatus(kontainerId, tidpunkt, longitude, latitude, noggranhet, status);
        }
        
        public WRT.Core.BLL.Kontainer[] HämtaKontainrar() {
            return base.Channel.HämtaKontainrar();
        }
    }
}
